# Generated by Django 4.2.8 on 2023-12-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0003_storagemanufacturer_storagebay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagebay',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='storagebay',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
