# Generated by Django 4.2.8 on 2023-12-31 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0105_customfield_min_max_values'),
        ('netbox_physical_storage', '0004_alter_storagebay_options_storagebay_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagedevice',
            name='storage_device_type',
        ),
        migrations.CreateModel(
            name='StorageDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(default='SATA', max_length=50)),
                ('model_number', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_physical_storage.storagemanufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_physical_storage.storagedevicetype'),
        ),
    ]
