# Generated by Django 4.2.8 on 2023-12-31 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0005_remove_storagedevice_storage_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedevice',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_physical_storage.storagedevicetype'),
        ),
    ]
