# Generated by Django 4.2.8 on 2023-12-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0006_alter_storagedevice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemanufacturer',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
