# Generated by Django 4.2.8 on 2023-12-31 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0007_storagemanufacturer_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagedevicetype',
            name='size',
            field=models.BigIntegerField(default=16, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
