# Generated by Django 4.2.8 on 2024-01-01 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0008_alter_storagedevicetype_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevice',
            name='storage_bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='netbox_physical_storage.storagebay'),
        ),
    ]
