# Generated by Django 4.2.8 on 2024-01-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0009_storagedevice_storage_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagedevicetype',
            name='form_factor',
            field=models.CharField(default='lff', max_length=50),
        ),
    ]
