# Generated by Django 4.2.8 on 2024-01-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_physical_storage', '0010_storagedevicetype_form_factor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagedevice',
            old_name='model',
            new_name='storage_device_model',
        ),
    ]
